[profile.default]
ffi = true
src = "src"
out = "out"
libs = ["lib"]
ast = true
build_info = true
gas_reports = ["*"]
extra_output = ["storageLayout"]

[profile.default.invariant]
fail_on_revert = true
runs = 10_000
depth = 15
dictionary_weight = 80
